### ISSUE TITLE
minor cleanup

### ISSUE THREAD

**Issue by awaxa** [reddit-diabetes/settings#1]
- [x] #2 straighten out raw conversion chart formatting
- [x] consider removing */5 values from conversion chart to save space
- [x] #3 remove trailing whitespace
- [x] #4 remove extra indendation from conversion math monospace block

**Comment by awaxa** [comment]
#3 removed trailing whitespace

**Comment by awaxa** [comment]
The conversion chart wastes a ton of real estate for users who disable our stylesheet.  I think removing the */5 values might help?

<img width="1392" alt="screen shot 2015-10-27 at 11 32 13 pm" src="https://cloud.githubusercontent.com/assets/979580/10781284/2ac386f6-7d03-11e5-912c-8a66b2289a98.png">
